language: python
python:
  - "2.7"
before_install:
   - wget -O - https://repo.saltstack.com/apt/ubuntu/12.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
   - echo deb http://repo.saltstack.com/apt/ubuntu/12.04/amd64/latest precise main | sudo tee /etc/apt/sources.list.d/saltstack.list
   - sudo apt-get -qq update
   - echo 127.0.0.1 | sudo tee -a /etc/hosts
   - sudo apt-get install -y salt-minion salt-master
   - sleep 5
   - sudo salt-key -A -y
script: salt '*' test.ping
